services:
  scorpion:
    build:
      context: ./scorpion
    container_name: scorpion_container
    networks:
      - arachinida_network

  spider:
    build:
      context: ./spider
    container_name: spider_container
    networks:
      - arachinida_network

  bonus:
    build:
      context: ./bonus
    container_name: bonus_container
    ports:
      - "8080:80"
    networks:
      - arachinida_network

networks:
  arachinida_network:
    driver: bridge
