name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential curl libcurl4-openssl-dev libexiv2-dev

    - name: Build and Test Spyder
      run: |
        cd spyder
        make clean
        make
        # Run some basic tests, replace with actual test commands
        ./spyder -l 1 https://42.fr
      continue-on-error: true # Continue even if this step fails for better error reporting

    - name: Build and Test Scorpion
      run: |
        cd scorpion
        make clean
        make
        # Run some basic tests, replace with actual test commands
        ./scorpion -l example.jpg
      continue-on-error: true # Continue even if this step fails for better error reporting

